### ISSUE TITLE
doesn't start after reboot

### ISSUE THREAD

**Issue by louisabraham** [foundObjects/zram-swap#1]
Hi, I installed zram-swap with the PKGBUILD [there](https://forum.pine64.org/showthread.php?tid=8812).

It works well but doesn't activate after a restart.

**Comment by foundObjects** [comment]
I haven't done too much testing on Arch derived distros unfortunately. What output do you get from `systemctl status zram-swap` at boot before you start the service manually? Is there anything in the log snipped that indicates a script failure somewhere? If not, if the service just isn't starting for some reason, try `systemctl enable zram-swap` and see if it was somehow disabled post install.

**Comment by louisabraham** [comment]
Thanks for your reply!

It looks like the PKGBUILD just doesn't starts the service.
So I just launched those commands after install:

```
sudo systemctl daemon-reload
sudo systemctl enable zram-swap.service
sudo systemctl start zram-swap.service
```
