### ISSUE TITLE
Use more CPU resource to get more RAM resource

### ISSUE THREAD

**Issue by SYK696** [foundObjects/zram-swap#11]
My cpu resource is enough,but raspiberryhas only 512MB ram.I want to use more cpu resource to get more resource.

**Comment by reukiodo** [comment]
According to https://linuxreviews.org/Comparison_of_Compression_Algorithms you should try using zstd, which zram already supports. Have you tried all 4 different options mentioned in the https://github.com/foundObjects/zram-swap/blob/master/service/zram-swap.config ?

**Comment by foundObjects** [comment]
As mentioned above just select a compression algorithm with a higher compression ratio, zstd is likely what you want.
